version = 1


[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
coverage_report = "./TestResults/Reports/Cobertura.xml" 

[coverage]
paths = ["TestResults/Reports/Cobertura.xml"]

[coverage.format]
type = "cobertura"
