version = 1

test_patterns = [
    "tests/**/*.cs"
]

exclude_patterns = [
    "tests/**"
]

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
coverage_report = "./TestResults/Reports/Cobertura.xml" 

[coverage]
paths = ["TestResults/Reports/Cobertura.xml"]

[coverage.format]
type = "cobertura"
